### ISSUE TITLE
[PENDING] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [codemonkeyricky/lightning-grep#1]
Dear @codemonkeyricky,
Could you be so kind to generate ```.exe``` for the rest of us who are merely users w/o compiler?

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by codemonkeyricky** [comment]
@sergeevabc Thanks for your interest. Unfortunately I don't really have the bandwidth at the moment to support this feature right now. For my own curiosity, are you interested in using this tool to improve productivity?

**Comment by codemonkeyricky** [comment]
On second thought I'll see if I could find a moment this weekend - no promises though :)

**Comment by sergeevabc** [comment]
> Are you interested in using this tool to improve productivity?

Am looking for fast tools to do simple tasks, e.g. search accumulated prose, lyrics, dictionaries by pattern.

**Comment by sergeevabc** [comment]
Is there anything a mere user like me could do to expedite a resolution of this issue?
